# approve_images_v2.py
import logging
import json
import os
import shutil
from pathlib import Path
from dotenv import load_dotenv
import argparse
import threading
import time

# Import project modules
try:
    import config_v2 as config # Use v2 config
    import web_approver_v2 as web_approver # Imports the Flask app and interaction functions (use v2)
except ImportError as e:
    print(f"ERROR: Failed to import necessary v2 modules: {e}")
    print("Make sure config_v2.py and web_approver_v2.py exist and are correct.")
    exit(1)

# --- Logging Setup ---
log_file_path = Path(config.LOG_FILE)
try:
    log_file_path.parent.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s',
        handlers=[
            logging.FileHandler(log_file_path, mode='a'),
            logging.StreamHandler()
        ]
    )
except Exception as e:
    print(f"ERROR setting up logging: {e}")
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s', handlers=[logging.StreamHandler()])
log = logging.getLogger(__name__)

# --- Helper: Sanitize Name ---
def sanitize_name(name):
    """Sanitizes a name for file/folder usage."""
    return "".join(c for c in name if c.isalnum() or c in (' ', '_')).rstrip().replace(' ', '_')

# --- Helper Function to Find Latest API_OUTPUTS Run Folder ---
def find_latest_api_output_run_dir(api_outputs_base: Path) -> Path | None:
    """
    Find the most recently modified subdirectory within the API_OUTPUTS base directory.
    Returns the Path object or None.
    """
    api_outputs_dir = api_outputs_base / config.API_OUTPUTS_SUBDIR
    if not api_outputs_dir.exists() or not api_outputs_dir.is_dir():
        log.error(f"{config.API_OUTPUTS_SUBDIR} directory does not exist: {api_outputs_dir}")
        return None

    # Get all subdirectories within API_OUTPUTS
    subdirs = [d for d in api_outputs_dir.iterdir() if d.is_dir()]
    if not subdirs:
        log.error(f"No run subdirectories found in {api_outputs_dir}")
        return None

    # Find the latest based on modification time
    try:
        latest_subdir = max(subdirs, key=lambda d: d.stat().st_mtime)
        log.info(f"Found latest API run directory: {latest_subdir}")
        return latest_subdir
    except Exception as e:
        log.error(f"Error finding latest directory in {api_outputs_dir}: {e}", exc_info=True)
        return None


# --- Function to Scan for Candidate Swapped Images in API Output ---
def find_candidate_swapped_images(api_run_dir: Path):
    """
    Scans the specific ComfyUI API run directory for character folders and their swapped images.
    Returns a dict: {actor_name: {character_name: str, candidates: [dicts], movie_name: str}}
    Candidate dict: {filename, relative_path_for_web, full_path_on_disk}
    """
    all_candidates = {}
    if not api_run_dir or not api_run_dir.is_dir():
        log.error(f"Invalid API run directory provided: {api_run_dir}")
        return all_candidates

    log.info(f"Scanning API run directory for swapped images: {api_run_dir}")

    # Extract Movie Name and Theme from the run folder name for display purposes
    # Assumes format: Movie_Theme_ProjectTimestamp_RunTimestamp
    parts = api_run_dir.name.split('_')
    movie_name_display = parts[0] if parts else "Unknown Movie"
    # theme_display = parts[1] if len(parts) > 1 else "Unknown Theme" # Could add theme if needed

    # Iterate through potential character__actor folders generated by ComfyUI run
    for char_actor_dir in api_run_dir.iterdir(): # e.g., Jai__Amitabh_Bachchan
        if not char_actor_dir.is_dir(): continue

        # Try parsing actor and character name (assuming format CharName__ActorName)
        dir_name_parts = char_actor_dir.name.split('__')
        if len(dir_name_parts) == 2:
             char_name_approx = dir_name_parts[0].replace('_', ' ') # Convert underscore back for display
             actor_name = dir_name_parts[1].replace('_', ' ')
             log.debug(f"Parsed folder: Char='{char_name_approx}', Actor='{actor_name}' from '{char_actor_dir.name}'")
        else:
             # Fallback if parsing fails (shouldn't happen if generate_images is correct)
             actor_name = char_actor_dir.name.replace('_', ' ')
             char_name_approx = actor_name # Best guess
             log.warning(f"Could not parse standard CharName__ActorName from folder '{char_actor_dir.name}'. Using folder name as actor: '{actor_name}'.")

        # Look in the correct ComfyUI output subfolder for swapped images
        swapped_images_dir = char_actor_dir / config.COMFYUI_SWAPPED_IMAGES_SUBFOLDER

        actor_data = {"character_name": char_name_approx, "candidates": [], "movie_name": movie_name_display}

        if swapped_images_dir.exists() and swapped_images_dir.is_dir():
            log.debug(f"Scanning swapped images in: {swapped_images_dir}")
            for img_file in swapped_images_dir.iterdir():
                # Check if it's a file and has a common image extension
                if img_file.is_file() and img_file.suffix.lower() in ['.jpg', '.jpeg', '.png', '.webp']:
                    try:
                        # PATH FOR WEB SERVER: Relative to COMFYUI_OUTPUT_DIR base
                        # Example: API_OUTPUTS/Sholay...RunID/Jai__Amitabh_Bachchan/swapped_images/swapped_medium_001.png
                        # This path is used in the HTML template's <img> src attribute.
                        relative_path_for_web = img_file.relative_to(config.COMFYUI_OUTPUT_DIR.resolve()).as_posix()

                        # FULL PATH ON DISK: Absolute path for file operations (copying)
                        full_path_on_disk = img_file.resolve()

                        actor_data["candidates"].append({
                            "filename": img_file.name,
                            "relative_path_for_web": relative_path_for_web, # Used by Flask template
                            "full_path_on_disk": str(full_path_on_disk) # Used for copying later
                        })
                    except ValueError as e:
                         # This error happens if img_file is not inside COMFYUI_OUTPUT_DIR
                         log.error(f"PATH ERROR: Cannot make '{img_file}' relative to '{config.COMFYUI_OUTPUT_DIR}'. Check config or file location. Error: {e}")
                    except Exception as e_gen:
                         log.warning(f"Error processing image file {img_file}: {e_gen}")

            if actor_data["candidates"]:
                 log.info(f"Found {len(actor_data['candidates'])} candidate swapped images for Actor: {actor_name} (Character: {char_name_approx})")
            else:
                 log.debug(f"No valid swapped image files found in {swapped_images_dir}")
        else:
             log.debug(f"Swapped images directory not found or not a directory: {swapped_images_dir}")

        # Only add actor if candidates were found
        if actor_data["candidates"]:
            # Use Actor Name as the primary key, as convention requires
            if actor_name in all_candidates:
                log.warning(f"Duplicate actor name key found: '{actor_name}'. Overwriting previous data. Check folder naming convention in ComfyUI output.")
            all_candidates[actor_name] = actor_data
        else:
             log.info(f"No candidates found for Actor: {actor_name} (Character: {char_name_approx}) in expected location.")

    if not all_candidates:
         log.warning(f"No candidate images found in any subfolder of {api_run_dir}")

    return all_candidates

# --- Script Execution ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Approve generated character images via web UI (V2). Operates on API_OUTPUTS folder.")
    parser.add_argument("-r", "--run_folder_path", help="Path to the specific API run folder within API_OUTPUTS. If not provided, uses the latest.")
    args = parser.parse_args()

    # --- Determine Target API Run Folder Path ---
    api_run_folder_to_process = None
    api_outputs_base = config.COMFYUI_OUTPUT_DIR # Base H:/dancers_content

    if args.run_folder_path:
        provided_path = Path(args.run_folder_path)
        # Basic validation: check if it exists and seems to be inside the expected base
        if provided_path.is_dir() and str(provided_path.resolve()).startswith(str(api_outputs_base.resolve() / config.API_OUTPUTS_SUBDIR)):
            api_run_folder_to_process = provided_path.resolve()
            log.info(f"Using provided API run folder: {api_run_folder_to_process}")
        else:
             log.error(f"Provided path '{args.run_folder_path}' is not a valid directory or not within '{api_outputs_base / config.API_OUTPUTS_SUBDIR}'. Exiting.")
             exit(1)
    else:
        log.info(f"Finding latest API run folder in {api_outputs_base / config.API_OUTPUTS_SUBDIR}...")
        api_run_folder_to_process = find_latest_api_output_run_dir(api_outputs_base)
        if not api_run_folder_to_process:
             log.error(f"No API run folder found in {api_outputs_base / config.API_OUTPUTS_SUBDIR}. Run generate_images first. Exiting."); exit(1)
        log.info(f"Using latest API run folder: {api_run_folder_to_process}")

    # --- Scan for Candidate Images in the chosen API Run Folder ---
    all_candidates_for_web = find_candidate_swapped_images(api_run_folder_to_process)
    if not all_candidates_for_web:
        log.error(f"No candidate swapped images found in the API run directory '{api_run_folder_to_process}'. Cannot start approval process. Exiting.")
        exit(1)

    # --- Start Flask Approver App Thread ---
    # Ensure the correct v2 web_approver functions are called
    flask_thread = threading.Thread(target=web_approver.run_flask_approver_app, daemon=True)
    flask_thread.start()
    log.info(f"Flask server starting in background thread on port {config.FLASK_PORT}...")
    time.sleep(2) # Give server a moment to start

    # --- Present Approval Page and Wait for User Submission ---
    # Pass the candidates found in the API run output folder
    approvals_dict = web_approver.present_image_approval_page(all_candidates_for_web)

    # --- Process Approvals ---
    if approvals_dict is None:
        log.error("No approvals received (timeout or error). Exiting.")
        # Consider stopping the Flask thread gracefully if possible/needed
        exit(1)

    log.info("\n--- Processing Approvals ---")
    log.debug(f"Raw approvals dictionary received: {approvals_dict}")

    # Define the destination directory for approved images WITHIN THE API RUN FOLDER
    api_run_approved_dir = api_run_folder_to_process / config.APPROVED_IMAGES_FOLDER_NAME
    api_run_approved_dir.mkdir(parents=True, exist_ok=True)
    log.info(f"Ensured approved images directory exists: {api_run_approved_dir}")

    # This dictionary will store the final paths of the COPIED approved images
    # Keys: Actor Name, Values: List of absolute paths to copied files in api_run_approved_dir OR "SKIPPED"
    copied_approved_files_map = {}

    for actor_name, selection_list in approvals_dict.items():
        # Actor Name here is the key used in the web UI and returned dict

        if isinstance(selection_list, str) and selection_list == "SKIP":
            log.info(f"User explicitly skipped actor: {actor_name}")
            copied_approved_files_map[actor_name] = "SKIPPED"
            continue
        elif not isinstance(selection_list, list) or not selection_list:
             # Handle cases where selection might be empty or not a list (shouldn't normally happen with current web form)
             log.info(f"No images marked as approved for actor: {actor_name} (and not skipped).")
             copied_approved_files_map[actor_name] = []
             continue # Go to next actor

        approved_paths_for_actor = [] # Stores paths of files successfully copied for THIS actor
        log.info(f"Processing {len(selection_list)} approved image path(s) for {actor_name}...")

        for idx, approved_img_source_path_str in enumerate(selection_list):
            try:
                # This is the FULL path to the candidate image in the ComfyUI output structure
                # (e.g., H:\dancers_content\API_OUTPUTS\...\Jai__Amitabh_Bachchan\swapped_images\swapped_medium_1.png)
                img_path_comfy_output = Path(approved_img_source_path_str)

                if not img_path_comfy_output.is_file():
                    log.warning(f"  - Approved image source path not found on disk: '{img_path_comfy_output}'. Skipping this image for {actor_name}.")
                    continue

                # Define the final filename for the approved image in the API run's approved folder
                actor_name_sanitized = sanitize_name(actor_name)
                # Try to determine shot type from the original filename for clarity
                shot_type = "unknown"
                if f"_{config.SWAPPED_IMAGE_PREFIX}medium_" in img_path_comfy_output.name.lower():
                    shot_type = "medium"
                elif f"_{config.SWAPPED_IMAGE_PREFIX}full_" in img_path_comfy_output.name.lower():
                    shot_type = "full"
                # Construct descriptive filename using Actor Name convention
                # e.g., Amitabh_Bachchan_approved_medium_1.png
                dest_filename = f"{actor_name_sanitized}_{config.APPROVED_IMAGE_PREFIX}{shot_type}_{idx+1}{img_path_comfy_output.suffix}"

                # Define the FULL destination path WITHIN the API run's approved folder
                dest_path_in_api_run = api_run_approved_dir / dest_filename

                # --- Perform the copy ---
                shutil.copy2(img_path_comfy_output, dest_path_in_api_run)
                log.info(f"  Copied approved image {idx+1} for {actor_name}:")
                log.info(f"    FROM: {img_path_comfy_output.name} (in {img_path_comfy_output.parent.name})")
                log.info(f"    TO:   {dest_path_in_api_run.name} (in {api_run_approved_dir.name})")

                # Store the ABSOLUTE path of the successfully copied file
                approved_paths_for_actor.append(str(dest_path_in_api_run.resolve()))

            except Exception as e:
                log.error(f"  Error copying approved image '{approved_img_source_path_str}' for {actor_name}: {e}", exc_info=True)
                # Continue to next image for the actor

        # Update the map with the list of successfully copied paths for this actor
        copied_approved_files_map[actor_name] = approved_paths_for_actor

    # --- Save the final map of COPIED approved files (paths within API run folder) ---
    # This JSON log resides WITHIN the API Run Folder it corresponds to.
    approval_log_path = api_run_folder_to_process / "approved_selections.json"
    try:
        with open(approval_log_path, "w", encoding="utf-8") as f:
            # Dump the dictionary containing the paths of the *copied* files
            json.dump(copied_approved_files_map, f, indent=2, ensure_ascii=False)
        log.info(f"Saved final approval results log (paths to copied files) to: {approval_log_path}")
    except IOError as e:
        log.error(f"Failed to save final approval log: {e}")

    print("\n" + "="*50)
    log.info("Approval process complete.")
    log.info(f"Approved images copied to: {api_run_approved_dir}")
    log.info(f"Details saved in: {approval_log_path}")
    print("\nYou may now proceed to the next step (e.g., video prompt generation).")
    print(f"Stop the Flask server (if running) by pressing Ctrl+C in this window.")
    print("="*50)
    # Consider adding logic to stop the Flask thread if desired, though daemon=True helps
    exit(0)