# config_v2.py (Updated for WanVideo Base Workflow)
import logging
from pathlib import Path
import sys

PROJECT_ROOT_DIR = Path(__file__).resolve().parent
print(f"[DEBUG] config_v2.py PROJECT_ROOT_DIR: {PROJECT_ROOT_DIR}")

# --- Logging ---
# Define a base log file name, scripts can append to it or use specific names
LOG_FILE_BASENAME = 'orchestrator_pipeline.log'
LOG_DIR = PROJECT_ROOT_DIR / "logs"

COMFYUI_INPUT_DIR = Path("D:/Comfy_UI_V20/ComfyUI/input").resolve()
COMFYUI_OUTPUT_DIR = Path("H:/dancers_content").resolve() # Base for ComfyUI outputs
IMAGE_WORKFLOW_TEMPLATE = str((Path(__file__).parent / "comfyui_workflows" / "API_flux_and_reactor.json").resolve())
COMFYUI_OUTPUT_DIR_BASE = Path(r"H:/dancers_content/API_OUTPUTS") # Correct
VIDEO_PARENT_SUBFOLDER = "all_videos"  # <<< REMOVE/COMMENT OUT
UPSCALE_SUBFOLDER = "4k_upscaled"      # <<< REMOVE/COMMENT OUT
CONSOLIDATED_4K_OUTPUT_DIR = ...       # <<< REMOVE/COMMENT OUT (No longer needed)

# --- Titles for Image Workflow (API_flux_and_reactor.json) ---
PROMPT_NODE_TITLE = "API_Prompt_Input" # Node 217 (Positive Prompt)
FACE_NODE_TITLE = "API_Face_Input" # Node 219 (Load Image for ReActor Face)
SEED_NODE_TITLE = "API_Seed_Input" # Node 216 (Noise Seed for Sampler)
SAVE_BASE_IMAGE_NODE_TITLE = "API_Base_Image_Output_SaveNode" # Node 607 (Save Image Base)
SAVE_SWAPPED_IMAGE_NODE_TITLE = "API_Image_Output_SaveNode" # Node 627 (Save Image Swapped)


# --- Core Paths ---
PROJECTS_BASE_DIR = PROJECT_ROOT_DIR / "Movie_Projects"

# --- ComfyUI Paths ---
COMFYUI_INPUT_DIR = Path("D:/Comfy_UI_V20/ComfyUI/input").resolve()  # YOUR PATH
COMFYUI_OUTPUT_DIR = Path("H:/dancers_content").resolve()          # YOUR PATH
API_OUTPUTS_SUBDIR = "API_OUTPUTS"

# --- Workflow Templates ---
WORKFLOW_TEMPLATE_DIR = PROJECT_ROOT_DIR / "comfyui_workflows"
# --- Point to the MODIFIED WanVideo workflow (NO Face Swap) ---
VIDEO_WORKFLOW_TEMPLATE = str((WORKFLOW_TEMPLATE_DIR / "API_wanvideo_v2_base.json").resolve()) # Path to comfyui_workflows/API_wanvideo_v2_base.json
# --- Point to the MODIFIED Reactor Face Swap workflow ---
REACTOR_WORKFLOW_TEMPLATE = str((WORKFLOW_TEMPLATE_DIR / "API_reactor_face_swap.json").resolve())

# --- Node Titles (Match API_wanvideo_v2_base.json EXACTLY) ---
# --- Titles for VIDEO Workflow (API_wanvideo_v2_base.json) ---
VIDEO_PROMPT_NODE_TITLE = "API_Positive_Prompt"          # Title of Positive Prompt Node
VIDEO_NEGATIVE_PROMPT_NODE_TITLE = "API_Negative_Prompt" # Title of Negative Prompt Node
VIDEO_SEED_NODE_TITLE = "API_Seed_Input"                 # Title of PrimitiveNode (Node 1211) - It takes the seed as 'value'
VIDEO_START_IMAGE_NODE_TITLE = "API_Video_Start_Image"    # Title of LoadAndResizeImage (Node 126)
# VIDEO_OUTPUT_PREFIX_NODE_TITLE = "API_Output_Prefix"      # Title of FileNamePrefix Node (Node 403)  # <<< REMOVED as node does not exist in this workflow
VIDEO_OUTPUT_SAVE_NODE_TITLE = "Video Combine 🎥🅥🅗🅢"         # Title of VHS_VideoCombine (Node 55) - FINAL OUTPUT

# --- Titles for FACE SWAP Workflow (API_reactor_face_swap.json) ---
REACTOR_SOURCE_FACE_NODE_TITLE = "API_Reactor_Source_Face"
REACTOR_TARGET_VIDEO_NODE_TITLE = "API_Reactor_Target_Video" # Will take video output
REACTOR_OUTPUT_PREFIX_NODE_TITLE = "API_Reactor_Output_Prefix"

# --- File Handling Prefixes ---
# Prefixes for files generated by ComfyUI in API_OUTPUTS
VIDEO_PREFIX = "vid_"                 # Prefix for generated video files
# (Optional) Add a prefix for swapped files if desired
# SWAPPED_VIDEO_PREFIX = "swapped_"

# --- Folder Names ---
# ** Project Folder Structure (`PROJECTS_BASE_DIR/...`) **
CHARACTERS_FOLDER_NAME = "characters"
SOURCE_ACTORS_FOLDER_NAME = "source_actors"
APPROVED_IMAGES_FOLDER_NAME = "approved_images" # <--- CORRECTED FOLDER NAME
# ** API Output Folder Structure (`COMFYUI_OUTPUT_DIR/API_OUTPUTS/...`) **
# Subfolders within the specific Run/Character__Actor folder in API_OUTPUTS
# (Define based on what the Save nodes in the workflow create)
COMFYUI_VIDEO_SUBFOLDER = "" # Video Combine might save directly in the Character__Actor folder if prefix node has no custom_dir set
# This will be created inside the Character__Actor folder in the API Run Output
FINAL_VIDEO_SWAPPED_FOLDER_NAME = "final_video_swapped"

# --- Core Configuration ---
COMFYUI_URL = "http://127.0.0.1:8188"
FLASK_PORT = 5002 # Port for approval UIs

# --- API Keys (Names only - actual keys stay in .env) ---
TAVILY_API_KEY_NAME = "TAVILY_API_KEY"
# Remove others if not used by any script in the pipeline
GEMINI_API_KEY_NAME = "GEMINI_API_KEY"
TMDB_API_KEY_NAME = "TMDB_API_KEY"

# --- Web Search & Image Gathering ---
# Constants likely not needed by this video script, but harmless to keep
TAVILY_SEARCH_COUNT = 10
FACE_FILTER_REQUIRED_COUNT = 1

# --- Web Selector / Approver ---
WEB_SELECTOR_TIMEOUT = 1800
WEB_APPROVER_TIMEOUT = 1800

# --- .env Path ---
DOTENV_PATH = PROJECT_ROOT_DIR / ".env"

# --- Video Generation Defaults (Optional - can override via Python) ---
# These could be read from config if you don't want them hardcoded in generate_videos.py
# DEFAULT_VIDEO_STEPS = 20
# DEFAULT_VIDEO_CFG = 6.0
# DEFAULT_VIDEO_SCHEDULER = "unipc"
# DEFAULT_VIDEO_SAMPLER = "euler_ancestral" # Or whatever sampler KSampler/WanVideoSampler uses